### ISSUE TITLE
Errors with modules and in some code files Example: import btc.txn

### ISSUE THREAD

**Issue by maxcado** [christianb93/bitcoin#2]
Looks like you've done a lot of work with this code. Just wanted to  let you know that there are numerous issues. To start, there are issues with the modules. For instance when using SendMoney.py get this:
   File "SendMoney.py", line 42, in <module>
    import btc.txn
 File txn.py line 35, in <module> from . import script
File script.py, line 38  in <module> from btc import utils, btc.utils

There are numerous syntax errors. For instance,  with btc.utils.

**Comment by christianb93** [comment]
There could be a couple of reasons for that:
* use `python --version` to determine your Python version. I use Python 3, depending on your setup and Linux distribution, you might have to use `python3` explictly instead of `python`
* you will also get errors when some libraries, like ecdsa, are not installed. If that happens, make sure to use `pip3` to install
* and of course you need to execute the script from within the directory where it is located

I just checked out a fresh version and did run the script successfully using Python3, so most likely this is the problem. Please try that again

Of course, you also need a bitcoind running and listening on port 18332, with sufficient balance - please see the instructions in [this](https://leftasexercise.com/2018/04/14/setting-up-and-testing-our-bitcoin-network/) and [this](https://leftasexercise.com/2018/04/27/creating-and-signing-a-bitcoin-transaction-from-scratch/) post on my blog for which the code was originally written (not sure if you came from there.....)

**Comment by christianb93** [comment]
Closing this as not reproduced
